# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter the name of the Course (e.g. Callaway Gardens)', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter the name of the Course and Tee box (e.g. Callaway Gardens - White)', max_length=200, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.Course', verbose_name='Course Id')),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the format', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter the name of the hole', max_length=200, null=True)),
                ('number', models.CharField(help_text='Enter the number of the hole', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the player', max_length=200)),
                ('handicap_index', models.DecimalField(decimal_places=1, help_text='Enter the handicap index', max_digits=3, verbose_name='Current Handicap Index')),
                ('high_handicap_index', models.DecimalField(decimal_places=1, help_text='Enter the high handicap index', max_digits=3, verbose_name='High Handicap Index')),
                ('low_handicap_index', models.DecimalField(decimal_places=1, help_text='Enter the low handicap index', max_digits=3, verbose_name='Low Handicap Index')),
                ('ghin_number', models.IntegerField(help_text='Enter the players GHIN number', verbose_name='GHIN Number')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handicap_index', models.DecimalField(decimal_places=1, help_text='Enter the players handicap index at time of tournament', max_digits=3, verbose_name='Handicap Index')),
                ('course_handicap', models.IntegerField(help_text='Enter the course handicap at time of tournament', verbose_name='Course Handicap')),
                ('total_in', models.IntegerField(help_text='Enter the score of the front 9 holes', verbose_name='IN')),
                ('total_out', models.IntegerField(help_text='Enter the score of the back 9 holes', verbose_name='OUT')),
                ('total', models.IntegerField(help_text='Enter the total score for the round', verbose_name='Total')),
                ('net', models.IntegerField(help_text='Enter the net score for the round', verbose_name='Course Handicap')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.Player', verbose_name='Player Id')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Enter the score for the hole', verbose_name='Score')),
                ('hole_played', models.IntegerField(blank=True, help_text='Enter the hole number played (e.g. in shotgun start if this is hole 16, but the second hole played enter 2)', null=True, verbose_name='Hole Played')),
            ],
        ),
        migrations.CreateModel(
            name='Tee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yardage', models.IntegerField(help_text='Enter the yardage for the tee', verbose_name='Yardage')),
                ('par', models.PositiveSmallIntegerField(help_text='Enter the par for this tee', verbose_name='Par')),
                ('handicap', models.PositiveSmallIntegerField(help_text='Enter the handicap for this tee', verbose_name='Handicap')),
                ('course_tee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.CourseTee', verbose_name='Course Id')),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.Hole', verbose_name='Hole Id')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the tournament (e.g. John Doe Memorial)', max_length=200, verbose_name='Name')),
                ('date', models.DateField(verbose_name='Date')),
                ('course_tee', models.ManyToManyField(blank=True, help_text='Select the courses and tees players are playing and set the default for the card', null=True, to='golf.CourseTee', verbose_name='Course and tee')),
                ('courses', models.ManyToManyField(help_text='Select the courses players are playing and set the default for the card', to='golf.Course', verbose_name='Courses')),
                ('format', models.ForeignKey(blank=True, help_text='Select the tournament format', null=True, on_delete=django.db.models.deletion.SET_NULL, to='golf.Format', verbose_name='Format')),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='tee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.Tee', verbose_name='Hole and Tee Id'),
        ),
        migrations.AddField(
            model_name='round',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='golf.Tournament', verbose_name='Tournament Id'),
        ),
    ]
