# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='Select the courses players are playing and set the default for the card', null=True, to='golf.Course', verbose_name='Courses'),
        ),
    ]
