# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_auto_20170719_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='default',
            field=models.BooleanField(default=False, help_text='Set a default for faster starts to putting scores in', verbose_name='Default'),
        ),
        migrations.AddField(
            model_name='course',
            name='priority',
            field=models.IntegerField(default=-1, help_text='Highest priority will be listed first in selecting format', verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='coursetee',
            name='default',
            field=models.BooleanField(default=False, help_text='Set a default for faster starts to putting scores in', verbose_name='Default'),
        ),
        migrations.AddField(
            model_name='coursetee',
            name='priority',
            field=models.IntegerField(default=-1, help_text='Highest priority will be listed first in selecting format', verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='format',
            name='default',
            field=models.BooleanField(default=False, help_text='Set a default for faster starts to putting scores in', verbose_name='Default'),
        ),
        migrations.AddField(
            model_name='format',
            name='priority',
            field=models.IntegerField(default=-1, help_text='Highest priority will be listed first in selecting format', verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='player',
            name='priority',
            field=models.IntegerField(default=-1, help_text='Highest priority will be listed first in selecting format', verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='tee',
            name='course_tee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.CourseTee', verbose_name='Course Tee Id'),
        ),
    ]
