# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0004_auto_20170720_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='hole',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='golf.Course', verbose_name='Course this hole belongs to'),
        ),
    ]
