# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0005_hole_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hole',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='golf.Course', verbose_name='Course this hole belongs to'),
            preserve_default=False,
        ),
    ]
