# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0006_auto_20170728_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetee',
            name='slope',
            field=models.IntegerField(default=113, help_text='Enter the slope for this course and tee', verbose_name='Slope'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursetee',
            name='course',
            field=models.ForeignKey(default=113, on_delete=django.db.models.deletion.CASCADE, to='golf.Course', verbose_name='Course Id'),
        ),
    ]
