# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0007_auto_20170731_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetee',
            name='color',
            field=models.IntegerField(default=0, help_text='Enter the number associated with the tee color', verbose_name='Tee Color'),
            preserve_default=False,
        ),
    ]
