# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0009_auto_20170731_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetee',
            name='short_color',
            field=models.IntegerField(choices=[(0, 'N'), (1, 'Y'), (2, 'GR'), (3, 'R'), (4, 'W'), (5, 'BU'), (6, 'BA'), (7, 'GO')], default=0, help_text='Enter the number associated with the tee color initials (0:None:N,1:Yellow:Y,2:Green:GR,3:Red:R,4:White:W,5:Blue:BU,6:Black:BA,7:Gold:G)', verbose_name='Tee Color Initials'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursetee',
            name='color',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Yellow'), (2, 'Green'), (3, 'Red'), (4, 'White'), (5, 'Blue'), (6, 'Black'), (7, 'Gold')], help_text='Enter the number associated with the tee color (0:None,1:Yellow,2:Green,3:Red,4:White,5:Blue,6:Black,7:Gold)', verbose_name='Tee Color'),
        ),
    ]
