# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0010_auto_20170803_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter the name of the club', max_length=200, null=True)),
                ('club_number', models.IntegerField(help_text='Enter the club number', max_length=200)),
                ('assn_number', models.IntegerField(help_text='Enter the association number', max_length=200)),
                ('password', models.CharField(help_text='Enter the password for ghp.ghin.com', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='hole',
            name='number',
            field=models.IntegerField(help_text='Enter the number of the hole'),
        ),
    ]
