# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0011_auto_20170804_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='assn_number',
            field=models.IntegerField(help_text='Enter the association number for ghp.ghin.com', verbose_name='Association Number'),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_number',
            field=models.IntegerField(help_text='Enter the club number for ghp.ghin.com', verbose_name='Club Number'),
        ),
    ]
