# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0012_auto_20170804_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='password2',
            field=models.CharField(default='', help_text='Enter the password for ghp.ghin.com', max_length=200),
            preserve_default=False,
        ),
    ]
