# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0014_remove_club_password2'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The type of player is likely person, 2-man, 4-man', max_length=140)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='player_type',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='golf.PlayerType', verbose_name='Player Type'),
            preserve_default=False,
        ),
    ]
