# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0015_auto_20170808_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='assn_number',
        ),
        migrations.RemoveField(
            model_name='club',
            name='club_number',
        ),
        migrations.RemoveField(
            model_name='club',
            name='password',
        ),
        migrations.AddField(
            model_name='club',
            name='club_class_name',
            field=models.CharField(blank=True, help_text='Name of the class of your plugin', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='club_class_package',
            field=models.CharField(blank=True, help_text='Name of the file containing the class of your plugin', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='data',
            field=models.CharField(blank=True, help_text='Data such as username and password used to login to your clubs player data store', max_length=516, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.CharField(blank=True, help_text='Filename for logo', max_length=200, null=True),
        ),
    ]
