# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0016_auto_20170809_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='ghin_number',
        ),
        migrations.AddField(
            model_name='player',
            name='data',
            field=models.CharField(blank=True, help_text='Data such as club member number, address, age', max_length=516, null=True),
        ),
    ]
