# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0017_auto_20170809_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='club_member_number',
            field=models.IntegerField(default=-1, help_text='Enter the players club member number (GHIN number)', verbose_name='Club Member Number'),
        ),
        migrations.AlterField(
            model_name='player',
            name='data',
            field=models.CharField(blank=True, help_text='Data such as address, phone number, age', max_length=516, null=True),
        ),
    ]
