# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0021_playerplugin_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='date',
            field=models.DateField(blank=True, help_text='Enter the date for the scorecard', null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='finish_time',
            field=models.DateField(blank=True, help_text='Enter the finish time for the scorecard', null=True, verbose_name='Finish Time'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='tee_time',
            field=models.DateField(blank=True, help_text='Enter the tee time for the scorecard', null=True, verbose_name='Tee Time'),
        ),
    ]
