# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0022_auto_20170810_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundPayoutPlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter the name of the plugin', max_length=200, null=True)),
                ('class_package', models.CharField(blank=True, help_text='Name of the module (filename with the .py) containing the class of your plugin', max_length=200, null=True)),
                ('class_name', models.CharField(blank=True, help_text='Enter the name of the class with the module', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentPayoutPlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter the name of the plugin', max_length=200, null=True)),
                ('class_package', models.CharField(blank=True, help_text='Name of the module (filename with the .py) containing the class of your plugin', max_length=200, null=True)),
                ('class_name', models.CharField(blank=True, help_text='Enter the name of the class with the module', max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='last_updated',
            field=models.DateTimeField(blank=True, help_text='Last time the player plugin was used to get this player', null=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='course_tee',
            field=models.ManyToManyField(blank=True, help_text='Select the courses and tees players are playing', to='golf.CourseTee', verbose_name='Course and tee'),
        ),
    ]
