# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0023_auto_20170814_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, help_text='logo', max_length=200, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(help_text='Enter the name of the club', max_length=200),
        ),
    ]
