# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0025_auto_20170818_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundpayoutplugin',
            name='class_name',
            field=models.CharField(help_text='Enter the name of the class with the module', max_length=200),
        ),
        migrations.AlterField(
            model_name='roundpayoutplugin',
            name='class_package',
            field=models.CharField(help_text='Name of the module (filename with the .py) containing the class of your plugin', max_length=200),
        ),
        migrations.AlterField(
            model_name='roundpayoutplugin',
            name='name',
            field=models.CharField(help_text='Enter the name of the plugin', max_length=200),
        ),
    ]
