# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0026_auto_20170818_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='date',
        ),
        migrations.AddField(
            model_name='club',
            name='default_tournament_name',
            field=models.CharField(blank=True, help_text='Enter default prefix for a tournament name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='playerplugin',
            name='last_updated',
            field=models.DateTimeField(blank=True, help_text='Last time this player plugin was used to get player data', null=True, verbose_name='Last Updated'),
        ),
        migrations.AddField(
            model_name='tournamentdate',
            name='tournament',
            field=models.ForeignKey(blank=True, help_text='Select the tournament(s) played this date', null=True, on_delete=django.db.models.deletion.SET_NULL, to='golf.Tournament', verbose_name='Tournament Played'),
        ),
    ]
