# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0027_auto_20170823_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentdate',
            name='date',
            field=models.DateField(blank=True, help_text='Select the date for this tournament', null=True, verbose_name='Date'),
        ),
    ]
