# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0028_tournamentdate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='golf.Club', verbose_name='Club'),
        ),
        migrations.AlterField(
            model_name='course',
            name='priority',
            field=models.IntegerField(default=-1, help_text='Lowest number greater than 0 will be listed first in selecting format', verbose_name='Priority'),
        ),
    ]
