# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0029_auto_20170824_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerplugin',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='club',
            name='players_last_updated',
            field=models.DateTimeField(blank=True, help_text='Enter the date the players handicaps were last updated', null=True),
        ),
    ]
