# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0031_auto_20170825_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetee',
            name='short_color',
        ),
    ]
