# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0032_remove_coursetee_short_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text=b'Enter the title for this activity', max_length=40, null=True)),
                ('notes', models.CharField(blank=True, help_text=b'Enter the notes for this activity', max_length=200, null=True)),
                ('date', models.DateField(blank=True, help_text=b'Enter the date for the scorecard', null=True, verbose_name=b'Date')),
            ],
        ),
    ]
