# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0033_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='course_tee',
            new_name='course_tees',
        ),
    ]
