# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0035_auto_20170914_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='net_style',
            field=models.CharField(blank=True, help_text='Enter the background-color for the cell in net view', max_length=200, null=True, verbose_name='Style Applied to the Cell'),
        ),
        migrations.AddField(
            model_name='round',
            name='total_in_net',
            field=models.IntegerField(blank=True, help_text='Enter the net score for the back 9', null=True, verbose_name='Back 9 Net'),
        ),
        migrations.AddField(
            model_name='round',
            name='total_in_net_style',
            field=models.CharField(blank=True, help_text='Enter the background-color for the cell in net view', max_length=200, null=True, verbose_name='Style Applied to the Cell'),
        ),
        migrations.AddField(
            model_name='round',
            name='total_in_style',
            field=models.CharField(blank=True, help_text='Enter the background-color for the cell in gross view', max_length=200, null=True, verbose_name='Style Applied to the Cell'),
        ),
        migrations.AddField(
            model_name='round',
            name='total_out_net',
            field=models.IntegerField(blank=True, help_text='Enter the net score for the front nine', null=True, verbose_name='Front 9 Net'),
        ),
        migrations.AddField(
            model_name='round',
            name='total_out_net_style',
            field=models.CharField(blank=True, help_text='Enter the background-color for the cell in net view', max_length=200, null=True, verbose_name='Style Applied to the Cell'),
        ),
        migrations.AddField(
            model_name='round',
            name='total_out_style',
            field=models.CharField(blank=True, help_text='Enter the background-color for the cell in gross view', max_length=200, null=True, verbose_name='Style Applied to the Cell'),
        ),
        migrations.AddField(
            model_name='round',
            name='total_style',
            field=models.CharField(blank=True, help_text='Enter the background-color for the cell in gross view', max_length=200, null=True, verbose_name='Style Applied to the Cell'),
        ),
        migrations.AddField(
            model_name='score',
            name='score_net',
            field=models.IntegerField(blank=True, help_text='Enter the net score for the hole', null=True, verbose_name='Score Net'),
        ),
        migrations.AddField(
            model_name='score',
            name='score_net_style',
            field=models.CharField(blank=True, help_text='Enter the background-color for the cell in net view', max_length=200, null=True, verbose_name='External Scorer Name'),
        ),
        migrations.AddField(
            model_name='score',
            name='score_style',
            field=models.CharField(blank=True, help_text='Enter the background-color for the cell in gross view', max_length=200, null=True, verbose_name='Style Applied to the Cell'),
        ),
        migrations.AlterField(
            model_name='round',
            name='net',
            field=models.IntegerField(blank=True, help_text='Enter the net score for the round', null=True, verbose_name='Course Handicap'),
        ),
        migrations.AlterField(
            model_name='round',
            name='total',
            field=models.IntegerField(blank=True, help_text='Enter the total score for the round', null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='round',
            name='total_in',
            field=models.IntegerField(blank=True, help_text='Enter the score of the back 9 holes', null=True, verbose_name='IN'),
        ),
        migrations.AlterField(
            model_name='round',
            name='total_out',
            field=models.IntegerField(blank=True, help_text='Enter the score of the front 9 holes', null=True, verbose_name='OUT'),
        ),
    ]
