# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0037_auto_20170918_1653'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Format',
            new_name='FormatPlugin',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='format',
            new_name='format_plugin',
        ),
        migrations.AddField(
            model_name='round',
            name='course_tee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='golf.CourseTee', verbose_name='Course and Tee This Round was Played on'),
        ),
    ]
