# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0038_auto_20170918_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatplugin',
            name='class_package',
            field=models.CharField(blank=True, help_text='Name of the module (filename without the .py) containing the class of your plugin', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='playerplugin',
            name='class_package',
            field=models.CharField(blank=True, help_text='Name of the module (filename without the .py) containing the class of your plugin', max_length=200, null=True),
        ),
    ]
