# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0040_auto_20170922_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='web_site',
            field=models.CharField(blank=True, help_text='Enter the web site for the club', max_length=200, null=True),
        ),
    ]
