# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0041_auto_20171003_1709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
