# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0046_auto_20171013_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='tournament',
        ),
        migrations.AddField(
            model_name='round',
            name='tournament_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='golf.TournamentDate', verbose_name='Tournament and Date'),
        ),
    ]
