# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0047_auto_20171013_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the format', max_length=200)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.FormatPlugin')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of this round of the tournament (e.g. John Doe Memorial)', max_length=200, verbose_name='Name')),
                ('date_scheduled', models.DateField(blank=True, help_text='Date this round of the tournament was supposed to be played', null=True, verbose_name='Date Scheduled')),
                ('date_started', models.DateField(blank=True, help_text='Select the date started (rarely different than scheduled)for this tournament', null=True, verbose_name='Date Started')),
                ('date_finished', models.DateField(blank=True, help_text='Select the date finished (rarely different than scheduled)for this tournament', null=True, verbose_name='Date Finished')),
                ('course_tees', models.ManyToManyField(blank=True, help_text='Select the courses and tees players are playing', to='golf.CourseTee', verbose_name='Course and tee')),
                ('courses', models.ManyToManyField(blank=True, help_text='Select the courses players are playing and set the default for the card', to='golf.Course', verbose_name='Courses')),
                ('format', models.ForeignKey(blank=True, help_text='Select the tournament format', null=True, on_delete=django.db.models.deletion.SET_NULL, to='golf.Format', verbose_name='Format')),
            ],
        ),
        migrations.RemoveField(
            model_name='tournamentdate',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='round',
            name='tournament_date',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='tournament_date',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='course_tees',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='format_plugin',
        ),
        migrations.AddField(
            model_name='round',
            name='date_finished',
            field=models.DateField(blank=True, help_text='Select the date this round was finished', null=True, verbose_name='Date Finished'),
        ),
        migrations.AddField(
            model_name='round',
            name='date_started',
            field=models.DateField(blank=True, help_text='Select the date this round was started', null=True, verbose_name='Date Started'),
        ),
        migrations.AlterField(
            model_name='round',
            name='net_style',
            field=models.CharField(blank=True, help_text='Enter the background-color for the cell in net view', max_length=200, null=True, verbose_name='Style for total net style'),
        ),
        migrations.AlterField(
            model_name='round',
            name='total_in_net_style',
            field=models.CharField(blank=True, help_text='Enter the background-color for the cell in net view', max_length=200, null=True, verbose_name='Style for total in net style'),
        ),
        migrations.AlterField(
            model_name='round',
            name='total_in_style',
            field=models.CharField(blank=True, help_text='Enter the background-color for the cell in gross view', max_length=200, null=True, verbose_name='Style for total in gross style'),
        ),
        migrations.AlterField(
            model_name='round',
            name='total_out_net_style',
            field=models.CharField(blank=True, help_text='Enter the background-color for the cell in net view', max_length=200, null=True, verbose_name='Style for total out net style'),
        ),
        migrations.AlterField(
            model_name='round',
            name='total_out_style',
            field=models.CharField(blank=True, help_text='Enter the background-color for the cell in gross view', max_length=200, null=True, verbose_name='Style for total out gross style'),
        ),
        migrations.AlterField(
            model_name='round',
            name='total_style',
            field=models.CharField(blank=True, help_text='Enter the background-color for the cell in gross view', max_length=200, null=True, verbose_name='Style for total gross style'),
        ),
        migrations.DeleteModel(
            name='TournamentDate',
        ),
        migrations.AddField(
            model_name='tournamentround',
            name='tournament',
            field=models.ForeignKey(blank=True, help_text='Select the tournament', null=True, on_delete=django.db.models.deletion.SET_NULL, to='golf.Tournament', verbose_name='Tournament Played'),
        ),
        migrations.AddField(
            model_name='round',
            name='tournament_round',
            field=models.ForeignKey(blank=True, help_text='map to tournament round', null=True, on_delete=django.db.models.deletion.SET_NULL, to='golf.TournamentRound', verbose_name='Tournament Round'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='tournament_round',
            field=models.ForeignKey(blank=True, help_text='map to tournament round', null=True, on_delete=django.db.models.deletion.SET_NULL, to='golf.TournamentRound', verbose_name='Tournament Round'),
        ),
    ]
