# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0050_auto_20171019_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_net_style',
            field=models.CharField(blank=True, help_text='Enter the background-color for the cell in net view', max_length=200, null=True, verbose_name='Style for net score'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_style',
            field=models.CharField(blank=True, help_text='Enter the background-color for the cell in gross view', max_length=200, null=True, verbose_name='Style for gross'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='attest',
            field=models.ForeignKey(blank=True, help_text='Enter the player that attests the score', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_attest', to='golf.Player', verbose_name='Attest Player Id'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='external_attest',
            field=models.CharField(blank=True, help_text='Enter the name of the attest if it is not a player', max_length=200, null=True, verbose_name='External Attest Name'),
        ),
    ]
