# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0051_auto_20171019_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_style',
            field=models.CharField(blank=True, help_text='Enter the background-color for the cell in gross view', max_length=200, null=True, verbose_name='Style for gross score'),
        ),
    ]
