# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0052_auto_20171019_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='rank',
            field=models.IntegerField(blank=True, help_text='Enter the gross rank of this round in the tournament round', null=True, verbose_name='Gross Rank'),
        ),
        migrations.AddField(
            model_name='round',
            name='rank_net',
            field=models.IntegerField(blank=True, help_text='Enter the net rank of this round in the tournament round', null=True, verbose_name='Net Rank'),
        ),
    ]
