# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0054_auto_20171023_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='skin',
            field=models.BooleanField(default=False, help_text='Is this score evaluated as a skin? This changes with each scorecard submitted', verbose_name='Skin'),
        ),
    ]
