# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0057_auto_20171024_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='details',
            field=models.CharField(blank=True, help_text='Enter the details for this activity', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='suspicious',
            field=models.BooleanField(default=False, help_text='Is this suspicious activity', verbose_name='Suspicious'),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.CharField(blank=True, help_text='Enter the user for this activity', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(blank=True, help_text='Enter the date for this activity', null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='notes',
            field=models.CharField(blank=True, help_text='Enter the notes for this activity', max_length=500, null=True),
        ),
    ]
