# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0062_auto_20171113_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentRoundImportPlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the format', max_length=200)),
                ('priority', models.IntegerField(default=-1, help_text='Highest priority will be listed first in selecting importer', verbose_name='Priority')),
                ('class_package', models.CharField(blank=True, help_text='Name of the module (filename without the .py) containing the class of your plugin', max_length=200, null=True)),
                ('class_name', models.CharField(blank=True, help_text='Enter the name of the class with the module', max_length=200, null=True)),
            ],
        ),
    ]
