# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0063_tournamentroundimportplugin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerplugin',
            old_name='class_package',
            new_name='class_module',
        ),
        migrations.RemoveField(
            model_name='tournamentround',
            name='format_data',
        ),
        migrations.AddField(
            model_name='playerplugin',
            name='filename',
            field=models.CharField(blank=True, help_text='Name of the module (filename) containing the class of your plugin', max_length=200, null=True, verbose_name='Filename'),
        ),
        migrations.AddField(
            model_name='playerplugin',
            name='version',
            field=models.IntegerField(blank=True, default=1, help_text='Incrementing version number to keep names unique', null=True, verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='tournamentround',
            name='data',
            field=models.CharField(blank=True, help_text='Data such as username and password used to login to your clubs player data store (used by your plugin)', max_length=516, null=True),
        ),
        migrations.AlterField(
            model_name='playerplugin',
            name='name',
            field=models.CharField(blank=True, help_text='Enter the name of the plugin', max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.DeleteModel(
            name='FormatData',
        ),
    ]
