# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0064_auto_20171201_0421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formatplugin',
            old_name='class_package',
            new_name='class_module',
        ),
        migrations.RenameField(
            model_name='payoutplugin',
            old_name='class_package',
            new_name='class_module',
        ),
        migrations.RenameField(
            model_name='tournamentroundimportplugin',
            old_name='class_package',
            new_name='class_module',
        ),
        migrations.AddField(
            model_name='formatplugin',
            name='filename',
            field=models.CharField(blank=True, help_text='Name of the module (filename) containing the class of your plugin', max_length=200, null=True, verbose_name='Filename'),
        ),
        migrations.AddField(
            model_name='formatplugin',
            name='version',
            field=models.IntegerField(blank=True, default=1, help_text='Incrementing version number to keep names unique', null=True, verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='payoutplugin',
            name='data',
            field=models.CharField(blank=True, help_text='Data such as username and password used to login to your clubs player data store (used by your plugin)', max_length=516, null=True),
        ),
        migrations.AddField(
            model_name='payoutplugin',
            name='filename',
            field=models.CharField(blank=True, help_text='Name of the module (filename) containing the class of your plugin', max_length=200, null=True, verbose_name='Filename'),
        ),
        migrations.AddField(
            model_name='payoutplugin',
            name='version',
            field=models.IntegerField(blank=True, default=1, help_text='Incrementing version number to keep names unique', null=True, verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='playerplugin',
            name='data',
            field=models.CharField(blank=True, help_text='Data such as username and password used to login to your clubs player data store (used by your plugin)', max_length=516, null=True),
        ),
        migrations.AddField(
            model_name='tournamentroundimportplugin',
            name='filename',
            field=models.CharField(blank=True, help_text='Name of the module (filename) containing the class of your plugin', max_length=200, null=True, verbose_name='Filename'),
        ),
        migrations.AddField(
            model_name='tournamentroundimportplugin',
            name='version',
            field=models.IntegerField(blank=True, default=1, help_text='Incrementing version number to keep names unique', null=True, verbose_name='Version'),
        ),
    ]
