# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0065_auto_20171201_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formatplugin',
            name='class_module',
        ),
        migrations.RemoveField(
            model_name='payoutplugin',
            name='class_module',
        ),
        migrations.RemoveField(
            model_name='playerplugin',
            name='class_module',
        ),
        migrations.RemoveField(
            model_name='tournamentroundimportplugin',
            name='class_module',
        ),
        migrations.AddField(
            model_name='tournamentroundimportplugin',
            name='data',
            field=models.CharField(blank=True, help_text='Data such as username and password used to login to your clubs player data store (used by your plugin)', max_length=516, null=True),
        ),
    ]
