# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0066_auto_20171201_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerplugin',
            name='filename',
        ),
        migrations.AddField(
            model_name='playerplugin',
            name='class_module',
            field=models.FileField(null=True, upload_to='playerplugin'),
        ),
        migrations.AlterField(
            model_name='playerplugin',
            name='class_name',
            field=models.CharField(blank=True, help_text='Enter the name of the class within the module', max_length=200, null=True),
        ),
    ]
