# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0067_auto_20171201_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerplugin',
            name='class_archive',
            field=models.FileField(help_text='The file uploaded by the user', null=True, upload_to='uploads/playerplugin'),
        ),
        migrations.AlterField(
            model_name='playerplugin',
            name='class_module',
            field=models.CharField(blank=True, help_text='Enter the name of the class module', max_length=200, null=True),
        ),
    ]
