# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0068_auto_20171201_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerplugin',
            name='priority',
            field=models.IntegerField(default=-1, help_text='Highest priority will be listed first in selecting format', verbose_name='Priority'),
        ),
    ]
