# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0070_auto_20171203_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatplugin',
            name='class_archive',
            field=models.FileField(help_text='The file uploaded by the user', null=True, upload_to='uploads/formatplugin'),
        ),
    ]
