# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0071_auto_20171203_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentroundimportplugin',
            name='filename',
        ),
        migrations.AddField(
            model_name='tournamentroundimportplugin',
            name='class_archive',
            field=models.FileField(help_text='The file uploaded by the user', null=True, upload_to='uploads/formatplugin'),
        ),
        migrations.AddField(
            model_name='tournamentroundimportplugin',
            name='class_module',
            field=models.CharField(blank=True, help_text='Enter the name of the class module', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tournamentroundimportplugin',
            name='description',
            field=models.CharField(blank=True, help_text='Enter the description of the format', max_length=512, null=True),
        ),
    ]
