# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0074_auto_20180103_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerplugin',
            name='class_module_name',
            field=models.CharField(blank=True, help_text='The name of the class module', max_length=200, null=True),
        ),
    ]
