# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0075_playerplugin_class_module_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerplugin',
            name='class_archive_name',
            field=models.CharField(blank=True, help_text='The name of the file uploaded by the user', max_length=200, null=True),
        ),
    ]
