# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0076_playerplugin_class_archive_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatplugin',
            name='class_archive_name',
            field=models.CharField(blank=True, help_text='The name of the file uploaded by the user', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='formatplugin',
            name='class_module_name',
            field=models.CharField(blank=True, help_text='The name of the class module provided by the user', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tournamentroundimportplugin',
            name='class_archive_name',
            field=models.CharField(blank=True, help_text='The name of the file uploaded by the user', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tournamentroundimportplugin',
            name='class_module_name',
            field=models.CharField(blank=True, help_text='The name of the class module provided by the user', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='formatplugin',
            name='class_archive',
            field=models.FileField(help_text='The file uploaded by the user', null=True, upload_to='uploads/playerplugin'),
        ),
        migrations.AlterField(
            model_name='formatplugin',
            name='class_module',
            field=models.FileField(help_text='The class module file', null=True, upload_to='playerplugins'),
        ),
        migrations.AlterField(
            model_name='playerplugin',
            name='class_module_name',
            field=models.CharField(blank=True, help_text='The name of the class module provided by the user', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentroundimportplugin',
            name='class_archive',
            field=models.FileField(help_text='The file uploaded by the user', null=True, upload_to='uploads/playerplugin'),
        ),
        migrations.AlterField(
            model_name='tournamentroundimportplugin',
            name='class_module',
            field=models.FileField(help_text='The class module file', null=True, upload_to='playerplugins'),
        ),
    ]
