# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0078_auto_20180103_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundImportPlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the format', max_length=200)),
                ('description', models.CharField(blank=True, help_text='Enter the description of the round importer', max_length=512, null=True)),
                ('version', models.IntegerField(blank=True, default=1, help_text='Incrementing version number to keep names unique', null=True, verbose_name='Version')),
                ('class_archive', models.FileField(help_text='The file uploaded by the user', null=True, upload_to='uploads/roundimportplugin')),
                ('class_archive_name', models.CharField(blank=True, help_text='The name of the file uploaded by the user', max_length=200, null=True)),
                ('class_module', models.FileField(help_text='The class module file', null=True, upload_to='roundimportplugins')),
                ('class_module_name', models.CharField(blank=True, help_text='The name of the class module provided by the user', max_length=200, null=True)),
                ('class_name', models.CharField(blank=True, help_text='Enter the name of the class with the module', max_length=200, null=True)),
                ('priority', models.IntegerField(default=-1, help_text='Highest priority will be listed first in selecting importer', verbose_name='Priority')),
                ('data', models.CharField(blank=True, help_text='Data such as username and password used to login to your clubs player data store (used by your plugin)', max_length=516, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TournamentRoundImportPlugin',
        ),
    ]
